spring:
  rabbitmq:
#   host: localhost
    host: 106.10.50.175
    port: 5672
    username: kakaopay
    password: kakao1234
    virtualhost: kakaopay
    exchange: kakaopay
    topic: kakaopay

    queue-alarm: alarm

    queue-request: request
    queue-response: response
    queue-response-1: response1
    queue-response-2: response2

schedule:
  rabbitmq:
    cron: false
    timer: false

